import { afterAll, beforeAll, describe, expect, test } from "vitest";
import { Database, type Connection } from "../database";
import { OracleDriver } from "../drivers/oracle";
import { requireOraclePoolAttributes } from "../drivers/oracle-url";
import { Number as OraNumber, Varchar2 } from "../types/oracle";
import { sql } from "./sql";

const enabled = process.env["ORACLE_URL"] !== undefined;
const db = new Database();

class BuilderUsers extends db.Table("oracle_builder_users") {
  id = OraNumber.column({ nonNull: true });
  name = Varchar2.column({ nonNull: true });
  nickname = Varchar2.column();
}

class BuilderDefaults extends db.Table("oracle_builder_defaults") {
  id = OraNumber.column({ nonNull: true, generated: true });
  nickname = Varchar2.column();
}

describe.skipIf(!enabled)("Oracle builder execution", () => {
  let conn: Connection;

  beforeAll(async () => {
    conn = db.connect(await OracleDriver.create(requireOraclePoolAttributes()));
    for (const table of ["oracle_builder_users", "oracle_builder_defaults"]) {
      try {
        await conn.execute(sql`DROP TABLE ${db.scopedIdent(table)} PURGE`);
      } catch {
        // The table does not exist on the first run.
      }
    }
    await conn.execute(sql`
      CREATE TABLE ${db.scopedIdent("oracle_builder_users")} (
        ${db.scopedIdent("id")} NUMBER NOT NULL,
        ${db.scopedIdent("name")} VARCHAR2(100) NOT NULL,
        ${db.scopedIdent("nickname")} VARCHAR2(100) DEFAULT 'anonymous'
      )
    `);
    await conn.execute(sql`
      CREATE TABLE ${db.scopedIdent("oracle_builder_defaults")} (
        ${db.scopedIdent("id")} NUMBER GENERATED BY DEFAULT AS IDENTITY,
        ${db.scopedIdent("nickname")} VARCHAR2(100) DEFAULT 'anonymous'
      )
    `);
  });

  afterAll(async () => {
    for (const table of ["oracle_builder_users", "oracle_builder_defaults"]) {
      await conn.execute(sql`DROP TABLE ${db.scopedIdent(table)} PURGE`);
    }
    await conn.close();
  });

  test("insert, DEFAULT, pagination, update, and delete", async () => {
    await BuilderUsers.insert(
      { id: "1", name: "alice", nickname: "ally" },
      { id: "2", name: "bob" },
      { id: "3", name: "carol", nickname: "c" },
    ).execute();

    expect(
      await BuilderUsers.from()
        .select(({ oracle_builder_users: users }) => ({ id: users.id, name: users.name }))
        .orderBy(({ oracle_builder_users: users }) => users.id)
        .offset(1)
        .limit(1)
        .execute(),
    ).toEqual([{ id: "2", name: "bob" }]);

    await BuilderUsers.update()
      .where(({ oracle_builder_users: users }) => users.id.eq(2))
      .set(() => ({ nickname: "bobby" }))
      .execute();
    expect(
      await BuilderUsers.from()
        .where(({ oracle_builder_users: users }) => users.id.eq(2))
        .select(({ oracle_builder_users: users }) => ({ nickname: users.nickname }))
        .execute(),
    ).toEqual([{ nickname: "bobby" }]);

    await BuilderUsers.delete()
      .where(({ oracle_builder_users: users }) => users.id.eq(1))
      .execute();
    expect(
      await BuilderUsers.from()
        .select(({ oracle_builder_users: users }) => ({ id: users.id }))
        .execute(),
    ).toHaveLength(2);
  });

  test("all-default and VALUES-source inserts execute", async () => {
    await BuilderDefaults.insert({}).execute();
    expect(
      await BuilderDefaults.from()
        .select(({ oracle_builder_defaults: row }) => ({ nickname: row.nickname }))
        .execute(),
    ).toEqual([{ nickname: "anonymous" }]);

    expect(
      await db
        .values({ n: OraNumber.from("1"), label: Varchar2.from("one") }, { n: "2", label: "two" })
        .select(({ values }) => values)
        .orderBy(({ values }) => values.n)
        .execute(),
    ).toEqual([
      { n: "1", label: "one" },
      { n: "2", label: "two" },
    ]);
  });
});
