// SQLite dialect codegen entry — facts + type table + class chrome in,
// generated .ts files out via the unified emitter (../emission/emit.ts).
// All emission knowledge lives there; this file contributes DATA: the
// committed per-doc-page facts (docs/<page>.json — schema and
// extraction prompt in docs/index.ts), the sqlite type table, and the
// per-class chrome (imports/statics/heritage).
//
// The emitted surface is derived from the facts by global rules —
//   - method receivers = each overload's FIRST argument's domain
//     ("any" ⇒ universal); args are in exact SQL call order;
//   - names are camelCase(sql) for functions, symbol + PG-style
//     alias for operators.
// The only remaining judgment is EXCLUSIONS below. Every claim is
// mechanically checked by signatures.verify.test.ts against the real
// engine; its completeness gate ensures every pragma_function_list
// entry is either defined in the facts or excluded here.
//
// Run: node --experimental-strip-types src/types/sqlite/emit.ts
//      [--out-dir <dir>]   (codegen:check)

import * as fs from "node:fs";
import * as path from "node:path";
import { pathToFileURL } from "node:url";
import { DocPageSchema } from "./docs/index.ts";
import { type EmitFn } from "../emission/facts.ts";
import {
  writeGeneratedTree,
  chromeImportLines,
  metaDeclareLines,
  typnameStaticLines,
  scanOverrideNames,
  type ClassChrome,
  type EmitConfig,
  type TypeEntry,
} from "../emission/emit.ts";

const HEADER =
  "// Auto-generated by src/types/sqlite/emit.ts from docs/*.json — do not edit.\n";

// --- facts: one JSON per vendored doc page --------------------------------
// Loaded with fs (not import attributes — parser-neutral across node
// strip-types / swc / tsgo / tsdown) and zod-validated at import time:
// a malformed JSON fails loudly here, before any emission.

const PAGES = [
  "lang_corefunc",
  "lang_mathfunc",
  "lang_datefunc",
  "lang_aggfunc",
  "percentile",
  "json1",
  "lang_expr",
] as const;

export const SIGNATURES: EmitFn[] = PAGES.flatMap((page) => {
  const raw = fs.readFileSync(path.join(import.meta.dirname, "docs", `${page}.json`), "utf8");
  return DocPageSchema.parse(JSON.parse(raw)).functions;
});

// Functions typegres refuses to surface — the completeness gate's
// whitelist: every pragma_function_list entry must be either defined
// in the facts or listed here.
export const EXCLUSIONS: string[] = [
  // Window functions — typegres has no OVER-clause modeling yet (PG
  // doesn't either). Revisit with window support in the query builder.
  "row_number", "rank", "dense_rank", "percent_rank", "cume_dist", "ntile",
  "lag", "lead", "first_value", "last_value", "nth_value",
  // FTS / rtree / geopoly — only meaningful on virtual tables, which
  // typegres doesn't model.
  "bm25", "fts3_tokenizer", "fts5", "fts5_get_locale", "fts5_insttoken",
  "fts5_locale", "fts5_source_id", "highlight", "matchinfo", "offsets",
  "optimize", "snippet",
  "rtreecheck", "rtreedepth", "rtreenode",
  "geopoly_area", "geopoly_bbox", "geopoly_blob", "geopoly_ccw",
  "geopoly_contains_point", "geopoly_debug", "geopoly_group_bbox",
  "geopoly_json", "geopoly_overlap", "geopoly_regular", "geopoly_svg",
  "geopoly_within", "geopoly_xform",
  "match", // MATCH operator function — only meaningful on FTS virtual tables
  // Planner hints — no-ops for typing purposes; noise on the API.
  "likelihood", "likely", "unlikely",
  // Introspection / footguns.
  "load_extension", // loads native code — must not be reachable from a query builder
  "sqlite_compileoption_get", // build introspection
  "sqlite_compileoption_used", // build introspection
  "sqlite_offset", // low-level file-offset introspection
  "sqlite_log", // error-log side effect, returns nothing useful
  "subtype", // internal function-subtype plumbing
  // CURRENT_* keywords aren't callable syntax — the datetime functions
  // cover them (date('now'), time('now'), datetime('now')).
  "current_date", "current_time", "current_timestamp",
];

// The sqlite type table. No `generic`/`element` entries (sqlite has
// no containers or pseudotypes), so the emitter's T-threading
// machinery stays dormant; receiver-following returns come from
// `returns: "arg0"` in the facts instead.
const TYPES: TypeEntry[] = [
  {
    typname: "any",
    className: "Any",
    primitiveTsUnion: "number | string | boolean | Uint8Array",
  },
  // primitiveTs here is emitter DATA (arg unions + collision routing);
  // the runtime statics live in the hand-written overrides/<view>.ts.
  { typname: "integer", className: "Integer", primitiveTs: "number" },
  // integer and real share `number`; real outranks, so where twin
  // overloads agree on the return, numbers (fractional included)
  // dispatch through the value-preserving CAST(? AS REAL).
  { typname: "real", className: "Real", primitiveTs: "number", losslessRank: 1 },
  { typname: "text", className: "Text", primitiveTs: "string" },
  { typname: "blob", className: "Blob", primitiveTsUnion: "Uint8Array" },
  { typname: "bool", className: "Bool", primitiveTs: "boolean" },
];

const CONFIG: EmitConfig = {
  typeTable: new Map(TYPES.map((t) => [t.typname, t])),
  // Names owned by hand-written base members (bespoke typing on
  // SqlValue/Any).
  noMethod: new Set(["coalesce", "in"]),
};

// CAST/render target per class — the storage-class name, except bool:
// SQLite has no native bool, its storage class is INTEGER 0/1.
const CAST_TARGET: { [typname: string]: string } = { bool: "INTEGER" };

const PLACEMENT_DOC = `// Methods are placed by their receiver (first) argument's documented
// domain — runtime dispatch IS the type system for RPC callers
// (exoeval), so a value only carries the methods honest for its
// storage class.
// Every method: typed overload declarations over a runtime.match
// implementation (arg validation + primitive serialization + return
// class per matched overload — same dispatch model as PG).`;

const chromeFor = (typname: string): ClassChrome => {
  const lines: string[] = [HEADER.trimEnd()];

  if (typname === "any") {
    lines.push(`// The generated half of the SQLite root class (hand-written core —
// dialect metadata, isNull/isNotNull/in — extends this in
// ../overrides/any.ts). Carries ONLY the universal methods (receiver
// domain "any").`);
  } else {
    const cls = CONFIG.typeTable.get(typname)!.className;
    lines.push(`// ${cls}<N> — the ${typname} storage-class view: the __view brand
// (near-identical subclasses are otherwise structurally
// interchangeable, defeating nominal checks), [meta]/typname chrome,
// and the methods whose receiver domain is ${typname}. Hand-written
// behavior (deserialize, acceptsPrimitive) extends this in
// ../overrides/${typname}.ts.`);
  }
  lines.push(PLACEMENT_DOC);

  const parentImport = typname === "any"
    ? 'import { SqlValue } from "../../sql-value";'
    : 'import { Any } from "../overrides/any";';
  lines.push(...chromeImportLines(parentImport));

  const cls = CONFIG.typeTable.get(typname)!.className;
  lines.push(`export class ${cls}<in out N extends number> extends ${typname === "any" ? "SqlValue" : "Any"}<N> {`);

  // Every concrete class (everything but the root) gets the brand +
  // [meta] + typname chrome — same rule as PG. types.Cls refs: the
  // barrel exports the hand-written override, so nullability
  // transforms and runtime.pgType land on the full class.
  if (typname !== "any") {
    lines.push(`  declare readonly __view: "${typname}";`);
    lines.push(...metaDeclareLines(`types.${cls}`));
    lines.push(...typnameStaticLines(CAST_TARGET[typname] ?? typname.toUpperCase(), typname, true));
    lines.push("");
  }

  return { prologue: lines.join("\n"), epilogue: "}\n" };
};

const main = (): void => {
  const outDirFlag = process.argv.indexOf("--out-dir");
  const outDir =
    outDirFlag >= 0
      ? path.resolve(process.argv[outDirFlag + 1]!)
      : path.resolve(import.meta.dirname);

  writeGeneratedTree({
    generatedDir: path.join(outDir, "generated"),
    barrelPath: path.join(import.meta.dirname, "index.ts"),
    types: TYPES,
    facts: SIGNATURES,
    cfg: CONFIG,
    chromeFor: (t) => chromeFor(t.typname),
    overrides: scanOverrideNames(path.resolve(import.meta.dirname, "overrides")),
  });
  console.log(`Generated ${TYPES.length} classes in ${path.join(outDir, "generated")}`);
};

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
