declare module "cloudflare:test" {
  // Give the test env the bindings from wrangler.jsonc (Env comes from
  // worker-configuration.d.ts, generated by `wrangler types`).
  interface ProvidedEnv extends Env {}
}
